name: Terraform Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
    #   K3S_SERVER_IP: 114.218.145.161
      K3S_SERVER_IP: ${{ secrets.K3S_SERVER_IP }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.5.7'

    - name: Terraform Init
      run: terraform init

    - name: Apply main.tf (install Docker and k3s)
      run: terraform apply -auto-approve -target=null_resource.install_docker_k3s
      env:
        TF_VAR_ssh_password: ${{ secrets.SSH_PASSWORD }}
        TF_VAR_mysql_root_password: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        TF_VAR_ssh_host: ${{ secrets.K3S_SERVER_IP }}

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Copy k3s kubeconfig to user directory
      run: sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no arvin@${{ env.K3S_SERVER_IP }} "sudo cp /etc/rancher/k3s/k3s.yaml /home/arvin/k3s.yaml && sudo chown arvin:arvin /home/arvin/k3s.yaml"
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

    - name: Copy k3s kubeconfig to runner
      run: |
        mkdir -p $HOME/.kube
        sshpass -p ${{ secrets.SSH_PASSWORD }} scp -o StrictHostKeyChecking=no arvin@${{ env.K3S_SERVER_IP }}:/home/arvin/k3s.yaml $HOME/.kube/config
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

    - name: Apply k8s_resources.tf (deploy MySQL and Redis)
      run: terraform apply -auto-approve
      env:
        TF_VAR_ssh_password: ${{ secrets.SSH_PASSWORD }}
        TF_VAR_mysql_root_password: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        TF_VAR_ssh_host: ${{ secrets.K3S_SERVER_IP }}
        KUBECONFIG: $HOME/.kube/config
